# Generated by Django 4.2.7 on 2024-09-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_country_name_country_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
