# Generated by Django 4.2.7 on 2024-09-09 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_cartdetails_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartDetails',
            new_name='Cart',
        ),
    ]
