# Generated by Django 4.2.7 on 2024-09-16 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
