# Generated by Django 4.2.7 on 2024-09-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cartorderitem_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartelements',
            unique_together={('course', 'cart')},
        ),
    ]
