# Generated by Django 4.2.7 on 2024-09-18 18:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_orderitems_course_ordersdetails_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetails',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
