# Generated by Django 4.2.7 on 2024-09-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ordersdetails_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdetails',
            name='saved',
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='applied_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
