# Generated by Django 4.2.7 on 2024-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_ordersdetails_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
